import 'src/styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { useCounter } from '../hooks/useCounter';
import { useInputArray } from '../hooks/useInputArray';
import { useBgColor } from '../hooks/useBgColor';
import { ThemeProvider } from 'styled-components'
import { theme } from 'theme'

const App = ({ Component, pageProps }: AppProps) => {
  const counter = useCounter();
  const inputArray = useInputArray();
  useBgColor();

  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <ThemeProvider theme={theme}>
        <Component {...pageProps} {...counter} {...inputArray}/>
      </ThemeProvider>
    </div>
  );
}

export default App;
